<?php
declare(strict_types=1);

if (!function_exists('e') || !function_exists('asset_url')) {
    $bootstrapPath = __DIR__ . '/../../public/_bootstrap.php';
    if (is_file($bootstrapPath)) {
        require_once $bootstrapPath;
    }
}

$currentScript = basename((string) ($_SERVER['SCRIPT_NAME'] ?? 'index.php'));

$fixedMenuItems = [
    ['file' => 'index.php', 'label' => 'ダッシュボード'],
    ['file' => 'settings.php', 'label' => '設定'],
    ['file' => 'sync_floors.php', 'label' => 'フロア同期'],
    ['file' => 'sync_master.php', 'label' => 'マスタ同期'],
    ['file' => 'sync_items.php', 'label' => '商品同期'],
    ['file' => 'sync_logs.php', 'label' => '同期ログ'],
    ['file' => 'sitemap.php', 'label' => '管理ページ一覧'],
    ['file' => 'logout.php', 'label' => 'ログアウト'],
];

$menuItems = $fixedMenuItems;
$menuAutoGenerated = false;

if (function_exists('admin_discover_pages')) {
    try {
        $discovered = admin_discover_pages();
        if (is_array($discovered) && $discovered !== []) {
            $normalized = [];
            foreach ($discovered as $page) {
                if (!is_array($page)) {
                    continue;
                }

                $file = basename((string) ($page['file'] ?? ''));
                $label = trim((string) ($page['label'] ?? ''));
                if ($file === '' || $label === '') {
                    continue;
                }

                $normalized[] = ['file' => $file, 'label' => $label];
            }

            if ($normalized !== []) {
                $menuItems = $normalized;
                $menuAutoGenerated = true;
            }
        }
    } catch (Throwable $e) {
        // メニュー自動生成に失敗しても固定メニューで継続する。
    }
}

$flash = null;
if (function_exists('flash_get')) {
    $flash = flash_get();
}
?>
<!doctype html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <title><?= function_exists('e') ? e($title ?? (defined('APP_NAME') ? APP_NAME : 'Admin')) : htmlspecialchars((string)($title ?? 'Admin'), ENT_QUOTES, 'UTF-8') ?></title>
  <link rel="stylesheet" href="<?= function_exists('e') && function_exists('asset_url') ? e(asset_url('css/style.css')) : '/assets/css/style.css' ?>">
</head>
<body class="admin-page">
<header class="admin-topbar">
  <div class="admin-topbar__brand"><a href="<?= function_exists('e') && function_exists('admin_url') ? e(admin_url('index.php')) : '/admin/index.php' ?>">PinkClub FANZA 管理</a></div>
  <div class="admin-topbar__right">
    <a href="<?= function_exists('e') && function_exists('public_url') ? e(public_url('index.php')) : '/' ?>" target="_blank" rel="noopener noreferrer">フロント表示</a>
  </div>
</header>

<div class="admin-shell">
  <aside class="admin-sidebar" aria-label="管理メニュー">
    <nav>
      <p class="admin-sidebar__heading">メニュー</p>
      <?php if (!$menuAutoGenerated): ?>
        <p class="admin-form-note">固定メニュー（自動生成失敗時フォールバック）</p>
      <?php endif; ?>
      <ul class="admin-sidebar__list">
        <?php foreach ($menuItems as $item): ?>
          <?php $isActive = $currentScript === $item['file']; ?>
          <li>
            <a class="admin-menu__link <?= $isActive ? 'is-active' : '' ?>"
               href="<?= function_exists('e') && function_exists('admin_url') ? e(admin_url($item['file'])) : '/admin/' . rawurlencode((string)$item['file']) ?>"><?= function_exists('e') ? e($item['label']) : htmlspecialchars((string)$item['label'], ENT_QUOTES, 'UTF-8') ?></a>
          </li>
        <?php endforeach; ?>
      </ul>
    </nav>
  </aside>

  <main class="admin-main">
    <?php if (is_array($flash) && isset($flash['message'])): ?>
      <div class="admin-notice <?= ($flash['type'] ?? '') === 'success' ? 'admin-notice--success' : 'admin-notice--error' ?>">
        <p><?= function_exists('e') ? e((string)$flash['message']) : htmlspecialchars((string)$flash['message'], ENT_QUOTES, 'UTF-8') ?></p>
      </div>
    <?php endif; ?>
