SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS admins (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS settings (
  id INT UNSIGNED PRIMARY KEY,
  api_id VARCHAR(255) NULL,
  affiliate_id VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS dmm_sites (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  site_code VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS dmm_services (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  site_code VARCHAR(50) NOT NULL,
  service_code VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_services_site FOREIGN KEY (site_code) REFERENCES dmm_sites(site_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS dmm_floors (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  service_code VARCHAR(50) NOT NULL,
  floor_code VARCHAR(50) NOT NULL,
  name VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_service_floor (service_code, floor_code),
  CONSTRAINT fk_floor_service FOREIGN KEY (service_code) REFERENCES dmm_services(service_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS actresses (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  dmm_id VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  ruby VARCHAR(255) NULL,
  birthday VARCHAR(20) NULL,
  prefectures VARCHAR(255) NULL,
  image_url TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS genres LIKE actresses;
ALTER TABLE genres MODIFY dmm_id VARCHAR(64) NOT NULL UNIQUE;
CREATE TABLE IF NOT EXISTS makers LIKE actresses;
ALTER TABLE makers MODIFY dmm_id VARCHAR(64) NOT NULL UNIQUE;
CREATE TABLE IF NOT EXISTS series_master LIKE actresses;
ALTER TABLE series_master MODIFY dmm_id VARCHAR(64) NOT NULL UNIQUE;
CREATE TABLE IF NOT EXISTS authors LIKE actresses;
ALTER TABLE authors MODIFY dmm_id VARCHAR(64) NOT NULL UNIQUE;

CREATE TABLE IF NOT EXISTS items (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  content_id VARCHAR(128) NOT NULL UNIQUE,
  product_id VARCHAR(128) NULL,
  title TEXT NOT NULL,
  service_code VARCHAR(64) NULL,
  service_name VARCHAR(255) NULL,
  floor_code VARCHAR(64) NULL,
  floor_name VARCHAR(255) NULL,
  category_name VARCHAR(255) NULL,
  volume VARCHAR(255) NULL,
  review_count INT NULL,
  review_average DECIMAL(3,2) NULL,
  url TEXT NULL,
  affiliate_url TEXT NULL,
  image_list TEXT NULL,
  image_small TEXT NULL,
  image_large TEXT NULL,
  sample_movie_url_476 TEXT NULL,
  sample_movie_url_560 TEXT NULL,
  sample_movie_url_644 TEXT NULL,
  sample_movie_url_720 TEXT NULL,
  sample_movie_pc_flag TINYINT(1) NOT NULL DEFAULT 0,
  sample_movie_sp_flag TINYINT(1) NOT NULL DEFAULT 0,
  price_min_text VARCHAR(255) NULL,
  list_price_text VARCHAR(255) NULL,
  release_date DATE NULL,
  raw_json LONGTEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS item_actresses (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  item_id INT UNSIGNED NOT NULL,
  dmm_id VARCHAR(64) NULL,
  actress_name VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_item_actress_item FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS item_genres (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  item_id INT UNSIGNED NOT NULL,
  dmm_id VARCHAR(64) NULL,
  genre_name VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_item_genre_item FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS item_campaigns (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  item_id INT UNSIGNED NOT NULL,
  dmm_id VARCHAR(64) NULL,
  campaign_name VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_item_campaign_item FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS item_labels (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  item_id INT UNSIGNED NOT NULL,
  dmm_id VARCHAR(64) NULL,
  label_name VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_item_label_item FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS item_directors (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  item_id INT UNSIGNED NOT NULL,
  dmm_id VARCHAR(64) NULL,
  director_name VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_item_director_item FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sync_logs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  sync_type VARCHAR(50) NOT NULL,
  is_success TINYINT(1) NOT NULL,
  synced_count INT NOT NULL DEFAULT 0,
  message TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
